project_id = "afero-hub"

[functions.import-hunt]
verify_jwt = true
entrypoint = "./functions/import-hunt/index.ts"

[functions.eduzz-webhook]
verify_jwt = false
entrypoint = "./functions/eduzz-webhook/index.ts"

[auth]
site_url = "https://afero-hub.vercel.app/hub"
additional_redirect_urls = ["https://afero-hub.vercel.app/hub", "https://afero-hub.vercel.app/hub.html", "http://localhost:4377/index.html", "http://127.0.0.1:4377/index.html"]
jwt_expiry = 3600
enable_signup = true
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_anonymous_sign_ins = false
minimum_password_length = 8
password_requirements = "lower_upper_letters_digits"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = true
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 3600
